version: "3.4"

services:
    bookexchange:
      image: ${DOCKER_REGISTRY-}bookexchange
      build:
        context: .
        dockerfile: Dockerfile
      ports: 
        - "8000:80"
    
    neo4j_image:
      image: neo4j:latest
      ports:
        - "7687"
      restart: always